/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package piano;

import com.sun.org.apache.bcel.internal.generic.GETFIELD;
import java.awt.AWTException;
import java.awt.Robot;
import java.awt.event.KeyEvent;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;
import sun.java2d.pipe.hw.AccelDeviceEventNotifier;

/**
 *
 * @author Emanuel
 */
public class Piano extends javax.swing.JFrame {

    /**
     * Creates new form Piano
     */
    public Piano() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Piano");
        jButton4.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NOTA0 = new javax.swing.JLabel();
        NOTA1 = new javax.swing.JLabel();
        NOTA2 = new javax.swing.JLabel();
        NOTA3 = new javax.swing.JLabel();
        NOTA4 = new javax.swing.JLabel();
        NOTA5 = new javax.swing.JLabel();
        NOTA6 = new javax.swing.JLabel();
        NOTA7 = new javax.swing.JLabel();
        NOTA8 = new javax.swing.JLabel();
        NOTA9 = new javax.swing.JLabel();
        NOTAs0 = new javax.swing.JLabel();
        NOTAs1 = new javax.swing.JLabel();
        NOTAs2 = new javax.swing.JLabel();
        NOTAs3 = new javax.swing.JLabel();
        NOTAs4 = new javax.swing.JLabel();
        NOTAs5 = new javax.swing.JLabel();
        NOTAs6 = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        btnFolk = new javax.swing.JButton();
        btnFC = new javax.swing.JButton();
        btnCs = new javax.swing.JToggleButton();
        btnDs = new javax.swing.JToggleButton();
        btnFs = new javax.swing.JToggleButton();
        btnGs = new javax.swing.JToggleButton();
        btnAs = new javax.swing.JToggleButton();
        btnCs2 = new javax.swing.JToggleButton();
        btnDs2 = new javax.swing.JToggleButton();
        btnC1 = new javax.swing.JToggleButton();
        btnD1 = new javax.swing.JToggleButton();
        btnE1 = new javax.swing.JToggleButton();
        btnF1 = new javax.swing.JToggleButton();
        bntG1 = new javax.swing.JToggleButton();
        btnA1 = new javax.swing.JToggleButton();
        btnB1 = new javax.swing.JToggleButton();
        btnC2 = new javax.swing.JToggleButton();
        btnD2 = new javax.swing.JToggleButton();
        btnE2 = new javax.swing.JToggleButton();
        btnAlegria = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NOTA0.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        NOTA0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NOTA0.setLabelFor(btnC1);
        NOTA0.setText("C1");
        getContentPane().add(NOTA0, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 20, -1));

        NOTA1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        NOTA1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NOTA1.setLabelFor(btnC1);
        NOTA1.setText("D1");
        getContentPane().add(NOTA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 20, -1));

        NOTA2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        NOTA2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NOTA2.setLabelFor(btnC1);
        NOTA2.setText("E1");
        getContentPane().add(NOTA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 20, -1));

        NOTA3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        NOTA3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NOTA3.setLabelFor(btnC1);
        NOTA3.setText("F1");
        getContentPane().add(NOTA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 20, -1));

        NOTA4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        NOTA4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NOTA4.setLabelFor(btnC1);
        NOTA4.setText("G1");
        getContentPane().add(NOTA4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 20, -1));

        NOTA5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        NOTA5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NOTA5.setLabelFor(btnC1);
        NOTA5.setText("A1");
        getContentPane().add(NOTA5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 20, -1));

        NOTA6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        NOTA6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NOTA6.setLabelFor(btnC1);
        NOTA6.setText("B1");
        getContentPane().add(NOTA6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 20, -1));

        NOTA7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        NOTA7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NOTA7.setLabelFor(btnC1);
        NOTA7.setText("C2");
        getContentPane().add(NOTA7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 20, -1));

        NOTA8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        NOTA8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NOTA8.setLabelFor(btnC1);
        NOTA8.setText("E2");
        getContentPane().add(NOTA8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 20, -1));

        NOTA9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        NOTA9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NOTA9.setLabelFor(btnC1);
        NOTA9.setText("D2");
        getContentPane().add(NOTA9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, 20, -1));

        NOTAs0.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        NOTAs0.setForeground(new java.awt.Color(255, 255, 255));
        NOTAs0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NOTAs0.setLabelFor(btnC1);
        NOTAs0.setText("D1#");
        getContentPane().add(NOTAs0, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, 30));

        NOTAs1.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        NOTAs1.setForeground(new java.awt.Color(255, 255, 255));
        NOTAs1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NOTAs1.setLabelFor(btnC1);
        NOTAs1.setText("F1#");
        NOTAs1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(NOTAs1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, 30));

        NOTAs2.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        NOTAs2.setForeground(new java.awt.Color(255, 255, 255));
        NOTAs2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NOTAs2.setLabelFor(btnC1);
        NOTAs2.setText("G1#");
        getContentPane().add(NOTAs2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, -1, 30));

        NOTAs3.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        NOTAs3.setForeground(new java.awt.Color(255, 255, 255));
        NOTAs3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NOTAs3.setLabelFor(btnC1);
        NOTAs3.setText("A1#");
        getContentPane().add(NOTAs3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, 30));

        NOTAs4.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        NOTAs4.setForeground(new java.awt.Color(255, 255, 255));
        NOTAs4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NOTAs4.setLabelFor(btnC1);
        NOTAs4.setText("C2#");
        getContentPane().add(NOTAs4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, -1, 30));

        NOTAs5.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        NOTAs5.setForeground(new java.awt.Color(255, 255, 255));
        NOTAs5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NOTAs5.setLabelFor(btnC1);
        NOTAs5.setText("D2#");
        getContentPane().add(NOTAs5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, -1, 30));

        NOTAs6.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        NOTAs6.setForeground(new java.awt.Color(255, 255, 255));
        NOTAs6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NOTAs6.setLabelFor(btnC1);
        NOTAs6.setText("C1#");
        getContentPane().add(NOTAs6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, 30));

        btnMenu.setBackground(new java.awt.Color(184, 121, 20));
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/piano/back FINAL TAMAÑO.png"))); // NOI18N
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 30, 40));

        btnFolk.setBackground(new java.awt.Color(184, 121, 20));
        btnFolk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/piano/cancion FINAL TAMAÑO.png"))); // NOI18N
        btnFolk.setBorder(null);
        btnFolk.setBorderPainted(false);
        btnFolk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFolk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFolkActionPerformed(evt);
            }
        });
        getContentPane().add(btnFolk, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 30, 30));

        btnFC.setBackground(new java.awt.Color(184, 121, 20));
        btnFC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/piano/cancion FINAL TAMAÑO.png"))); // NOI18N
        btnFC.setBorder(null);
        btnFC.setBorderPainted(false);
        btnFC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFCActionPerformed(evt);
            }
        });
        getContentPane().add(btnFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 30, 30));

        btnCs.setBackground(new java.awt.Color(0, 0, 0));
        btnCs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCsMousePressed(evt);
            }
        });
        getContentPane().add(btnCs, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 50, 150));

        btnDs.setBackground(new java.awt.Color(0, 0, 0));
        btnDs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnDsMouseReleased(evt);
            }
        });
        getContentPane().add(btnDs, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 50, 150));

        btnFs.setBackground(new java.awt.Color(0, 0, 0));
        btnFs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnFsMousePressed(evt);
            }
        });
        getContentPane().add(btnFs, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 50, 150));

        btnGs.setBackground(new java.awt.Color(0, 0, 0));
        btnGs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnGsMousePressed(evt);
            }
        });
        getContentPane().add(btnGs, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 50, 150));

        btnAs.setBackground(new java.awt.Color(0, 0, 0));
        btnAs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAsMousePressed(evt);
            }
        });
        getContentPane().add(btnAs, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 50, 150));

        btnCs2.setBackground(new java.awt.Color(0, 0, 0));
        btnCs2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCs2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCs2MousePressed(evt);
            }
        });
        getContentPane().add(btnCs2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 50, 150));

        btnDs2.setBackground(new java.awt.Color(0, 0, 0));
        btnDs2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDs2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDs2MousePressed(evt);
            }
        });
        getContentPane().add(btnDs2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 50, 150));

        btnC1.setBackground(new java.awt.Color(255, 255, 255));
        btnC1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnC1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnC1MousePressed(evt);
            }
        });
        btnC1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnC1KeyPressed(evt);
            }
        });
        getContentPane().add(btnC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 80, 260));

        btnD1.setBackground(new java.awt.Color(255, 255, 255));
        btnD1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnD1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnD1MousePressed(evt);
            }
        });
        getContentPane().add(btnD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 90, 260));

        btnE1.setBackground(new java.awt.Color(255, 255, 255));
        btnE1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnE1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnE1MousePressed(evt);
            }
        });
        getContentPane().add(btnE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 80, 260));

        btnF1.setBackground(new java.awt.Color(255, 255, 255));
        btnF1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnF1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnF1MousePressed(evt);
            }
        });
        getContentPane().add(btnF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 80, 260));

        bntG1.setBackground(new java.awt.Color(255, 255, 255));
        bntG1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntG1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bntG1MousePressed(evt);
            }
        });
        getContentPane().add(bntG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 80, 260));

        btnA1.setBackground(new java.awt.Color(255, 255, 255));
        btnA1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnA1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnA1MousePressed(evt);
            }
        });
        getContentPane().add(btnA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 80, 260));

        btnB1.setBackground(new java.awt.Color(255, 255, 255));
        btnB1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnB1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnB1MousePressed(evt);
            }
        });
        getContentPane().add(btnB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 80, 260));

        btnC2.setBackground(new java.awt.Color(255, 255, 255));
        btnC2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnC2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnC2MousePressed(evt);
            }
        });
        getContentPane().add(btnC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 80, 260));

        btnD2.setBackground(new java.awt.Color(255, 255, 255));
        btnD2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnD2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnD2MousePressed(evt);
            }
        });
        getContentPane().add(btnD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 80, 260));

        btnE2.setBackground(new java.awt.Color(255, 255, 255));
        btnE2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnE2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnE2MousePressed(evt);
            }
        });
        getContentPane().add(btnE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 80, 260));

        btnAlegria.setBackground(new java.awt.Color(184, 121, 20));
        btnAlegria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/piano/cancion FINAL TAMAÑO.png"))); // NOI18N
        btnAlegria.setBorder(null);
        btnAlegria.setBorderPainted(false);
        btnAlegria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlegria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlegriaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlegria, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, 30, 30));

        jButton1.setBackground(new java.awt.Color(184, 121, 20));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/piano/icon Play.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 30, 30));

        jButton2.setBackground(new java.awt.Color(184, 121, 20));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/piano/icon Play.png"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, 30, 30));

        jButton3.setBackground(new java.awt.Color(184, 121, 20));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/piano/icon Play.png"))); // NOI18N
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, 30, 30));

        jButton4.setBackground(new java.awt.Color(184, 121, 20));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/piano/typing.png"))); // NOI18N
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton4KeyPressed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 50, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/piano/pant 2 (1).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 720, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFCActionPerformed
        // TODO add your handling code here:
        NotasMusicales1 n = new NotasMusicales1();
        n.setVisible(true);
    }//GEN-LAST:event_btnFCActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        Menu m = new Menu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnFolkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFolkActionPerformed
        // TODO add your handling code here:
        NotasMusicales2 n = new NotasMusicales2();
        n.setVisible(true);
    }//GEN-LAST:event_btnFolkActionPerformed

    private void btnAlegriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlegriaActionPerformed
        // TODO add your handling code here:
        NotasMusicales3 n = new NotasMusicales3();
        n.setVisible(true);
    }//GEN-LAST:event_btnAlegriaActionPerformed


    private void btnC1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnC1MousePressed
        playNota("notas/C1.wav");
    }//GEN-LAST:event_btnC1MousePressed

    private void btnD1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnD1MousePressed
        playNota("notas/D1.wav");
    }//GEN-LAST:event_btnD1MousePressed

    private void btnE1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnE1MousePressed
        playNota("notas/E1.wav");
    }//GEN-LAST:event_btnE1MousePressed

    private void btnF1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnF1MousePressed
        playNota("notas/F1.wav");
    }//GEN-LAST:event_btnF1MousePressed

    private void bntG1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntG1MousePressed
        playNota("notas/G1.wav");
    }//GEN-LAST:event_bntG1MousePressed

    private void btnA1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnA1MousePressed
        playNota("notas/A1.wav");
    }//GEN-LAST:event_btnA1MousePressed

    private void btnB1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnB1MousePressed
        playNota("notas/B1.wav");
    }//GEN-LAST:event_btnB1MousePressed

    private void btnC2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnC2MousePressed
        playNota("notas/C2.wav");
    }//GEN-LAST:event_btnC2MousePressed

    private void btnD2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnD2MousePressed
        playNota("notas/D2.wav");
    }//GEN-LAST:event_btnD2MousePressed

    private void btnE2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnE2MousePressed
        playNota("notas/E2.wav");
    }//GEN-LAST:event_btnE2MousePressed

    private void btnCsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCsMousePressed
        playNota("notas/C#1.wav");
    }//GEN-LAST:event_btnCsMousePressed

    private void btnDsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDsMousePressed
        playNota("notas/D#1.wav");
    }//GEN-LAST:event_btnDsMousePressed

    private void btnDsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDsMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDsMouseReleased

    private void btnFsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFsMousePressed
        playNota("notas/F#1.wav");
    }//GEN-LAST:event_btnFsMousePressed

    private void btnGsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGsMousePressed
        playNota("notas/G#1.wav");
    }//GEN-LAST:event_btnGsMousePressed

    private void btnAsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAsMousePressed
        playNota("notas/A#1.wav");
    }//GEN-LAST:event_btnAsMousePressed

    private void btnCs2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCs2MousePressed
        playNota("notas/C#2.wav");
    }//GEN-LAST:event_btnCs2MousePressed

    private void btnDs2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDs2MousePressed
        playNota("notas/D#2.wav");
    }//GEN-LAST:event_btnDs2MousePressed

    private void btnC1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnC1KeyPressed
        /*       if (evt.getKeyChar()=='a') {
         playNota("notas/C1.wav");
         }*/
    }//GEN-LAST:event_btnC1KeyPressed

    private void jButton4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyPressed
        if (evt.getKeyCode() == com.sun.glass.events.KeyEvent.VK_Q) {
            playNota("notas/C1.wav");
        } else {
            if (evt.getKeyCode() == com.sun.glass.events.KeyEvent.VK_W) {
                playNota("notas/D1.wav");
            } else {
                if (evt.getKeyCode() == com.sun.glass.events.KeyEvent.VK_E) {
                    playNota("notas/E1.wav");
                } else {
                    if (evt.getKeyCode() == com.sun.glass.events.KeyEvent.VK_R) {
                        playNota("notas/F1.wav");
                    } else {
                        if (evt.getKeyCode() == com.sun.glass.events.KeyEvent.VK_T) {
                            playNota("notas/G1.wav");
                        } else {
                            if (evt.getKeyCode() == com.sun.glass.events.KeyEvent.VK_Y) {
                                playNota("notas/A1.wav");
                            } else {
                                if (evt.getKeyCode() == com.sun.glass.events.KeyEvent.VK_U) {
                                    playNota("notas/B1.wav");
                                } else {
                                    if (evt.getKeyCode() == com.sun.glass.events.KeyEvent.VK_I) {
                                        playNota("notas/C2.wav");
                                    } else {
                                        if (evt.getKeyCode() == com.sun.glass.events.KeyEvent.VK_O) {
                                            playNota("notas/B2.wav");
                                        } else {
                                            if (evt.getKeyCode() == com.sun.glass.events.KeyEvent.VK_P) {
                                                playNota("notas/E2.wav");
                                            } else {
                                                if (evt.getKeyCode() == com.sun.glass.events.KeyEvent.VK_2) {
                                                    playNota("notas/C#1.wav");
                                                } else {
                                                    if (evt.getKeyCode() == com.sun.glass.events.KeyEvent.VK_3) {
                                                        playNota("notas/D#2.wav");
                                                    } else {
                                                        if (evt.getKeyCode() == com.sun.glass.events.KeyEvent.VK_5) {
                                                            playNota("notas/F#1.wav");
                                                        } else {
                                                            if (evt.getKeyCode() == com.sun.glass.events.KeyEvent.VK_6) {
                                                                playNota("notas/G#1.wav");
                                                            } else {
                                                                if (evt.getKeyCode() == com.sun.glass.events.KeyEvent.VK_7) {
                                                                    playNota("notas/A#1.wav");
                                                                } else {
                                                                    if (evt.getKeyCode() == com.sun.glass.events.KeyEvent.VK_9) {
                                                                        playNota("notas/C#2.wav");
                                                                    } else {
                                                                        if (evt.getKeyCode() == com.sun.glass.events.KeyEvent.VK_0) {
                                                                            playNota("notas/D#2.wav");
                                                                        }
                                                                    }
                                                                }

                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }


    }//GEN-LAST:event_jButton4KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            new Piano().cancionFelizCumpleanios();
        } catch (InterruptedException ex) {
            Logger.getLogger(Piano.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            new Piano().cancionPolishGirlFolk();
        } catch (InterruptedException ex) {
            Logger.getLogger(Piano.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            new Piano().cancionHimnoAlegria();
        } catch (InterruptedException ex) {
            Logger.getLogger(Piano.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Piano().setVisible(true);
            }
        });

    }

    public void playNota(String ruta) {
        try {
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File(ruta).getAbsoluteFile());
            Clip clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
        } catch (Exception ex) {
            System.out.println("Error with playing sound.");
            ex.printStackTrace();
        }
    }

    public void cancionFelizCumpleanios() throws InterruptedException{
        int C1 = 355;
        int C1s = 400;
        int D1 = 445;
        int D1s = 490;
        int E1 = 535;
        int F1 = 580;
        int F1s = 625;
        int G1 = 655;
        int G1s = 695;
        int A1 = 725;
        int A1s = 760;
        int B1 = 805;
        int C2 = 855;
        int C2s = 900;
        int D2 = 935;
        int D2s = 970;
        int E2 = 1010;
        int corto = 400;
        int medio = 600;
        int largo = 1200;
        try {
        Robot robot = new Robot();
        // Simulate a mouse
        Thread.sleep(medio);
        tocarNota(C1, robot, "notas/C1.wav");
        Thread.sleep(medio);
        tocarNota(C1, robot, "notas/C1.wav");
        Thread.sleep(corto);
        tocarNota(D1, robot, "notas/D1.wav");
        Thread.sleep(medio);
        tocarNota(C1, robot, "notas/C1.wav");
        Thread.sleep(medio);
        tocarNota(F1, robot, "notas/F1.wav");
        Thread.sleep(medio);
        tocarNota(E1, robot, "notas/E1.wav");
        Thread.sleep(largo); // ------------------------
        tocarNota(C1, robot, "notas/C1.wav");
        Thread.sleep(medio);
        tocarNota(C1, robot, "notas/C1.wav");
        Thread.sleep(corto);
        tocarNota(D1, robot, "notas/D1.wav");
        Thread.sleep(medio);
        tocarNota(C1, robot, "notas/C1.wav");
        Thread.sleep(medio);
        tocarNota(G1, robot, "notas/G1.wav");
        Thread.sleep(medio);
        tocarNota(F1, robot, "notas/F1.wav");
        Thread.sleep(largo); // ------------------------
        tocarNota(C1, robot, "notas/C1.wav");
        Thread.sleep(medio);
        tocarNota(C1, robot, "notas/C1.wav");
        Thread.sleep(corto);
        tocarNota(C2, robot, "notas/C2.wav");
        Thread.sleep(medio);
        tocarNota(A1, robot, "notas/A1.wav");
        Thread.sleep(medio);
        tocarNota(F1, robot, "notas/F1.wav");
        Thread.sleep(medio);
        tocarNota(E1, robot, "notas/E1.wav");
        Thread.sleep(medio);
        tocarNota(D1, robot, "notas/D1.wav");
        Thread.sleep(largo); // ------------------------
        tocarNota(A1, robot, "notas/A1.wav");
        Thread.sleep(medio);
        tocarNota(A1, robot, "notas/A1.wav");
        Thread.sleep(corto);
        tocarNota(G1, robot, "notas/G1.wav");
        Thread.sleep(medio);
        tocarNota(C1, robot, "notas/C1.wav");
        Thread.sleep(medio);
        tocarNota(D1, robot, "notas/D1.wav");
        Thread.sleep(medio);
        tocarNota(C1, robot, "notas/C1.wav");
        Thread.sleep(medio);
        } catch (AWTException e) {
            e.printStackTrace();
        }
    }
    
    public void cancionHimnoAlegria() throws InterruptedException{
        int C1 = 355;
        int C1s = 400;
        int D1 = 445;
        int D1s = 490;
        int E1 = 535;
        int F1 = 580;
        int F1s = 625;
        int G1 = 655;
        int G1s = 695;
        int A1 = 725;
        int A1s = 760;
        int B1 = 805;
        int C2 = 855;
        int C2s = 900;
        int D2 = 935;
        int D2s = 970;
        int E2 = 1010;
        int corto = 300;
        int medio = 500;
        int largo = 800;
        try {
        Robot robot = new Robot();
        // Simulate a mouse
        Thread.sleep(medio);
        tocarNota(E1, robot, "notas/E1.wav");
        Thread.sleep(medio+100);
        tocarNota(E1, robot, "notas/E1.wav");
        Thread.sleep(medio);
        tocarNota(F1, robot, "notas/F1.wav");
        Thread.sleep(medio);
        tocarNota(G1, robot, "notas/G1.wav");
        Thread.sleep(medio);
        tocarNota(G1, robot, "notas/G1.wav");
        Thread.sleep(medio);
        tocarNota(F1, robot, "notas/F1.wav");
        Thread.sleep(medio);
        tocarNota(E1, robot, "notas/E1.wav");
        Thread.sleep(medio);
        tocarNota(D1, robot, "notas/D1.wav");
        Thread.sleep(medio);
        tocarNota(C1, robot, "notas/C1.wav");
        Thread.sleep(medio);
        tocarNota(C1, robot, "notas/C1.wav");
        Thread.sleep(medio);
        tocarNota(D1, robot, "notas/D1.wav");
        Thread.sleep(medio);
        tocarNota(E1, robot, "notas/E1.wav");
        Thread.sleep(medio);
        tocarNota(E1, robot, "notas/E1.wav");
        Thread.sleep(largo);
        tocarNota(D1, robot, "notas/D1.wav");
        Thread.sleep(corto);
        tocarNota(D1, robot, "notas/D1.wav");
        // --------------------------------
        Thread.sleep(largo+200);
        tocarNota(E1, robot, "notas/E1.wav");
        Thread.sleep(medio);
        tocarNota(E1, robot, "notas/E1.wav");
        Thread.sleep(medio);
        tocarNota(F1, robot, "notas/F1.wav");
        Thread.sleep(medio);
        tocarNota(G1, robot, "notas/G1.wav");
        Thread.sleep(medio);
        tocarNota(G1, robot, "notas/G1.wav");
        Thread.sleep(medio);
        tocarNota(F1, robot, "notas/F1.wav");
        Thread.sleep(medio);
        tocarNota(E1, robot, "notas/E1.wav");
        Thread.sleep(medio);
        tocarNota(D1, robot, "notas/D1.wav");
        Thread.sleep(medio);
        tocarNota(C1, robot, "notas/C1.wav");
        Thread.sleep(medio);
        tocarNota(C1, robot, "notas/C1.wav");
        Thread.sleep(medio);
        tocarNota(D1, robot, "notas/D1.wav");
        Thread.sleep(medio);
        tocarNota(E1, robot, "notas/E1.wav");
        Thread.sleep(medio);
        tocarNota(D1, robot, "notas/D1.wav");
        Thread.sleep(largo);
        tocarNota(C1, robot, "notas/C1.wav");
        Thread.sleep(corto);
        tocarNota(C1, robot, "notas/C1.wav");
        // ---------------------
        Thread.sleep(largo+200);
        tocarNota(D1, robot, "notas/D1.wav");
        Thread.sleep(medio+100);
        tocarNota(D1, robot, "notas/D1.wav");
        Thread.sleep(medio);
        tocarNota(E1, robot, "notas/E1.wav");
        Thread.sleep(medio);
        tocarNota(C1, robot, "notas/C1.wav");
        Thread.sleep(medio);
        tocarNota(D1, robot, "notas/D1.wav");
        Thread.sleep(medio);
        tocarNota(E1, robot, "notas/E1.wav");
        Thread.sleep(corto);
        tocarNota(F1, robot, "notas/F1.wav");
        Thread.sleep(corto);
        tocarNota(E1, robot, "notas/E1.wav");
        Thread.sleep(medio);
        tocarNota(C1, robot, "notas/C1.wav");
        Thread.sleep(medio);
        tocarNota(D1, robot, "notas/D1.wav");
        Thread.sleep(medio);
        tocarNota(E1, robot, "notas/E1.wav");
        Thread.sleep(corto);
        tocarNota(F1, robot, "notas/F1.wav");
        Thread.sleep(corto);
        tocarNota(E1, robot, "notas/E1.wav");
        Thread.sleep(medio);
        tocarNota(D1, robot, "notas/D1.wav");
        Thread.sleep(medio);
        tocarNota(C1, robot, "notas/C1.wav");
        Thread.sleep(medio);
        tocarNota(D1, robot, "notas/D1.wav");
        Thread.sleep(medio);
        tocarNota(C1, robot, "notas/C1.wav");
        } catch (AWTException e) {
            e.printStackTrace();
        }
    }
    
        public void cancionPolishGirlFolk() throws InterruptedException{
        int C1 = 355;
        int C1s = 400;
        int D1 = 445;
        int D1s = 490;
        int E1 = 535;
        int F1 = 580;
        int F1s = 625;
        int G1 = 655;
        int G1s = 695;
        int A1 = 725;
        int A1s = 760;
        int B1 = 805;
        int C2 = 855;
        int C2s = 900;
        int D2 = 935;
        int D2s = 970;
        int E2 = 1010;
        int corto = 300;
        int medio = 400;
        int largo = 800;
        try {
        Robot robot = new Robot();
        // Simulate a mouse
        Thread.sleep(medio);
        tocarNota(D2, robot, "notas/D2.wav");
        Thread.sleep(medio+100);
        tocarNota(B1, robot, "notas/B1.wav");
        Thread.sleep(medio);
        tocarNota(D2, robot, "notas/D2.wav");
        Thread.sleep(medio);
        tocarNota(B1, robot, "notas/B1.wav");
        Thread.sleep(medio);
        tocarNota(D2, robot, "notas/D2.wav");
        Thread.sleep(medio);
        tocarNota(B1, robot, "notas/B1.wav");
        Thread.sleep(medio);
        tocarNota(G1, robot, "notas/G1.wav");
        Thread.sleep(largo);
        tocarNota(A1, robot, "notas/A1.wav");
        Thread.sleep(medio);
        tocarNota(C2, robot, "notas/C2.wav");
        Thread.sleep(medio);
        tocarNota(B1, robot, "notas/B1.wav");
        Thread.sleep(medio);
        tocarNota(A1, robot, "notas/A1.wav");
        Thread.sleep(medio);
        tocarNota(D2, robot, "notas/D2.wav");
        // ----------------------
        Thread.sleep(largo);
        tocarNota(D2, robot, "notas/D2.wav");
        Thread.sleep(medio);
        tocarNota(B1, robot, "notas/B1.wav");
        Thread.sleep(medio);
        tocarNota(D2, robot, "notas/D2.wav");
        Thread.sleep(medio);
        tocarNota(B1, robot, "notas/B1.wav");
        Thread.sleep(medio);
        tocarNota(D2, robot, "notas/D2.wav");
        Thread.sleep(medio);
        tocarNota(B1, robot, "notas/B1.wav");
        Thread.sleep(medio);
        tocarNota(G1, robot, "notas/G1.wav");
        Thread.sleep(largo);
        tocarNota(A1, robot, "notas/A1.wav");
        Thread.sleep(medio);
        tocarNota(C2, robot, "notas/C2.wav");
        Thread.sleep(medio);
        tocarNota(B1, robot, "notas/B1.wav");
        Thread.sleep(medio);
        tocarNota(A1, robot, "notas/A1.wav");
        Thread.sleep(medio);
        tocarNota(G1, robot, "notas/G1.wav");
        // ------------------------
        Thread.sleep(largo);
        tocarNota(A1, robot, "notas/A1.wav");
        Thread.sleep(corto+150);
        tocarNota(A1, robot, "notas/A1.wav");
        Thread.sleep(corto+150);
        tocarNota(C2, robot, "notas/C2.wav");
        Thread.sleep(corto+150);
        tocarNota(C2, robot, "notas/C2.wav");
        Thread.sleep(corto+150);
        tocarNota(B1, robot, "notas/B1.wav");
        Thread.sleep(corto+150);
        tocarNota(G1, robot, "notas/G1.wav");
        Thread.sleep(corto+150);
        tocarNota(D2, robot, "notas/D2.wav");
        // --------------------------
        Thread.sleep(medio+250);
        tocarNota(A1, robot, "notas/A1.wav");
        Thread.sleep(corto+150);
        tocarNota(C2, robot, "notas/C2.wav");
        Thread.sleep(corto+150);
        tocarNota(B1, robot, "notas/B1.wav");
        Thread.sleep(corto+150);
        tocarNota(A1, robot, "notas/A1.wav");
        Thread.sleep(corto+150);
        tocarNota(D2, robot, "notas/D2.wav");
        } catch (AWTException e) {
            e.printStackTrace();
        }
    }
    
    public void tocarNota(int nota, Robot robot, String ruta){
        robot.mouseMove(nota,350);
        playNota(ruta);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NOTA0;
    private javax.swing.JLabel NOTA1;
    private javax.swing.JLabel NOTA2;
    private javax.swing.JLabel NOTA3;
    private javax.swing.JLabel NOTA4;
    private javax.swing.JLabel NOTA5;
    private javax.swing.JLabel NOTA6;
    private javax.swing.JLabel NOTA7;
    private javax.swing.JLabel NOTA8;
    private javax.swing.JLabel NOTA9;
    private javax.swing.JLabel NOTAs0;
    private javax.swing.JLabel NOTAs1;
    private javax.swing.JLabel NOTAs2;
    private javax.swing.JLabel NOTAs3;
    private javax.swing.JLabel NOTAs4;
    private javax.swing.JLabel NOTAs5;
    private javax.swing.JLabel NOTAs6;
    private javax.swing.JToggleButton bntG1;
    private javax.swing.JToggleButton btnA1;
    private javax.swing.JButton btnAlegria;
    private javax.swing.JToggleButton btnAs;
    private javax.swing.JToggleButton btnB1;
    private javax.swing.JToggleButton btnC1;
    private javax.swing.JToggleButton btnC2;
    private javax.swing.JToggleButton btnCs;
    private javax.swing.JToggleButton btnCs2;
    private javax.swing.JToggleButton btnD1;
    private javax.swing.JToggleButton btnD2;
    private javax.swing.JToggleButton btnDs;
    private javax.swing.JToggleButton btnDs2;
    private javax.swing.JToggleButton btnE1;
    private javax.swing.JToggleButton btnE2;
    private javax.swing.JToggleButton btnF1;
    private javax.swing.JButton btnFC;
    private javax.swing.JButton btnFolk;
    private javax.swing.JToggleButton btnFs;
    private javax.swing.JToggleButton btnGs;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
